### ISSUE TITLE
Drupal 9 

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_events#24]
To update to Drupal 9 we will need the latest versions of date_recur and date_recur_modular

https://www.drupal.org/project/date_recur_modular/releases/3.0.0

https://www.drupal.org/project/date_recur/releases/3.0.0

**Comment by stephen-cox** [comment]
## Coding standards issues

```
FILE: /app/web/modules/contrib/localgov_events/localgov_events.install
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 38 | ERROR | The array declaration extends to column 96 (the limit
    |       | is 80). The array content should be split up over
    |       | multiple lines
----------------------------------------------------------------------


FILE: /app/web/modules/contrib/localgov_events/localgov_events.module
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 189 | ERROR | [x] Each PHP statement must be on a line by itself
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

**Comment by ekes** [comment]
After discussion heading toward a 2.0.0 version that supports Drupal 9; and a 1.0.0 supporting Drupal 8.
Each linked from the appropriate localgov profile 1.x and 2.x

To this end we're renaming branches https://github.com/localgovdrupal/localgov/issues/198#issuecomment-836551334

As we still want to get everyone onboard before 'master' disappears, rather than renaming it 2.x in the Github UI https://docs.github.com/en/github/administering-a-repository/renaming-a-branch I'll push a 2.x branch already and make a PR onto that for this; and manually go through the other PRs.

**Comment by ekes** [comment]
https://github.com/localgovdrupal/localgov_events/tree/feature/2.x/24-drupal-9
https://github.com/localgovdrupal/localgov_events/tree/2.x

This will then want a localgov_project 2.x that includes Drupal 9 that can be used in the `.github/workflows/test.yml`¹ and the localgov_project should checkout 2.x of localgov profile that includes the 2.x branch of this module.

¹ I'm guessing it might be possible to make a variable that then checks out the correct version of the localgov_project based on the branch, or something?
