### ISSUE TITLE
Events search

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_events#3]
Full spec here: https://github.com/localgovdrupal/localgov/issues/136

**Comment by stephen-cox** [comment]
@willguv @finnlewis It looks like it's not going to be possible to have a full text search _and_ recurring events. This is because the Date Recur module doesn't integrate with Search API yet. There's an issue for this, but no progress has been made, https://www.drupal.org/project/date_recur/issues/2911761, and it doesn't look like an easy fix - @ekes was the last person to comment on the issue, so might have some thoughts on this.

How critical are recurring events? The easiest thing is to drop them until the Date Recur module supports Search API. An alternative will be to drop the full text search, but this will create some extra work getting the facets to work without Search API. There maybe some alternatives to these two options, but there is limited time to get this fully working and work on this is largely blocked until we reach a decision on this.

**Comment by willguv** [comment]
Thanks for the info @stephen-cox. Recurring events will be critical once councils start using our Events functionality. I wonder though when this will be. Andy Wallis said that the Events in the BHCC site isn't getting a lot of use currently, due to the lockdown. We can check Tom and other councils too.

It would be good to chat through the options at Monday's stand up. Right now, it feels like the best option is to continue without recurring events so we have something to flow content into and test with users, then revisit at a later date. Let's decide next week.

**Comment by stephen-cox** [comment]
As discussed as standup - we will remove the text search functionality and keep the recurring dates. We could add a separate text search if there's time.

**Comment by stephen-cox** [comment]
@willguv @finnlewis Just to update you on this, I have a solution for this as long as you're happy with drop downs for the neighbourhood, cost and category filters. I hope to have something to demo quickly tomorrow at standup.
